# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawValue', models.DecimalField(decimal_places=2, max_digits=6)),
                ('modifier', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('frequence', models.CharField(choices=[('MONTH', 'MONTH'), ('QUARTER', 'QUARTER'), ('RELEASE', 'RELEASE')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='measure',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.Metric'),
        ),
    ]
